language: go
sudo: required
go:
- 1.9.3

install:
- curl -Lo mmake https://github.com/codekoala/mmake/releases/download/v1.3.0/mmake_linux_amd64
- chmod 755 ./mmake

script:
- ./mmake update -I ./include
- TAG=$TRAVIS_COMMIT ./mmake -I ./include all

deploy:
  provider: releases
  file_glob: true
  file: ./bin/*
  skip_cleanup: true
  overwrite: true
  on:
    repo: codekoala/aws-sign-proxy
    tags: true
    condition: $TRAVIS_GO_VERSION =~ ^1\.9(\.[0-9]+)?$
